---
swagger: 2.0
basePath: /prod
info:
    title: VoteApp
schemes:
    - https

paths:
    /vote:
        post:
            produces:
                - application/json
            responses:
                200:
                    description: 200 response
                    schema:
                        $ref: "#/definitions/Empty"
                    headers:
                        Access-Control-Allow-Origin:
                            type: string
            x-amazon-apigateway-integration:
                responses:
                    default:
                        statusCode: 200
                        responseParameters:
                            method.response.header.Access-Control-Allow-Origin: "'*'"
                # NOTE: Replace <<region>> and <<accountId>> fields
                #uri: arn:aws:apigateway:<<region>>:lambda:path/2015-03-31/functions/arn:aws:lambda:<<region>>:<<accountId>>:function:${stageVariables.LambdaFunctionName}/invocations
                uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:491984616337:function:${stageVariables.LambdaFunctionName}/invocations

                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
        options:
            consumes:
                - application/json
            produces:
                - application/json
            responses:
                200:
                    description: 200 response
                    schema:
                        $ref: "#/definitions/Empty"
                    headers:
                        Access-Control-Allow-Origin:
                            type: string
                        Access-Control-Allow-Methods:
                            type: string
                        Access-Control-Allow-Headers:
                            type: string
            x-amazon-apigateway-integration:
                responses:
                    default:
                        statusCode: 200
                        responseParameters:
                            method.response.header.Access-Control-Allow-Methods: "'POST'"
                            method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                            method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: when_no_match
                requestTemplates:
                    application/json: "{\"statusCode\": 200}"
                type: mock

definitions:
    Empty:
        type: object
        title: Empty Schema
